// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantApi.Data;

#nullable disable

namespace RestaurantApi.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20260205200321_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantApi.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This ain't your average burger. Topped with our tangy cheddar cheese sauce, fresh lettuce, and tomato.",
                            Image = "burger.jpg",
                            Name = "Burger",
                            Price = 8.99m,
                            Tags = "[\"Lunch\",\"Dinner\",\"Spicy\"]"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Delicious french toast with banana and blueberry.",
                            Image = "banana-french-toast.jpg",
                            Name = "Banana Blueberry French Toast",
                            Price = 9.99m,
                            Tags = "[\"Breakfast\"]"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Creole-style pasta that's guaranteed to make you sweat.",
                            Image = "cajun-pasta.jpg",
                            Name = "Cajun Pasta",
                            Price = 16.99m,
                            Tags = "[\"Lunch\",\"Dinner\",\"Spicy\"]"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Delicious assortment of locally-sourced meats, cheeses, and spreads.",
                            Image = "charcuterie.jpg",
                            Name = "Charcuterie Board",
                            Price = 14.99m,
                            Tags = "[\"Appetizer\"]"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Heavenly cheesecake with a sweet raspberry topping.",
                            Image = "cheesecake.jpg",
                            Name = "Raspberry Cheesecake",
                            Price = 7.99m,
                            Tags = "[\"Dessert\"]"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Our outrageous chicken sandwich topped with pickled onions and jalapenos.",
                            Image = "chicken-slammer.jpg",
                            Name = "Chicken Slammer",
                            Price = 11.99m,
                            Tags = "[\"Lunch\",\"Dinner\",\"Spicy\"]"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Decadent chocolate pudding topped with chocolate cookies, chocolate frosting, and whipped cream.",
                            Image = "death-by-chocolate.jpg",
                            Name = "Death by Chocolate",
                            Price = 8.99m,
                            Tags = "[\"Dessert\"]"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Delicious assortment of unique donuts. Guaranteed to please!",
                            Image = "donuts.jpg",
                            Name = "Pile 'O Donuts",
                            Price = 6.99m,
                            Tags = "[\"Dessert\"]"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Spiced meatballs served with a rich tomato sauce.",
                            Image = "italian-meatballs.jpg",
                            Name = "Italian Meatballs",
                            Price = 13.99m,
                            Tags = "[\"Dinner\"]"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Delicious lamb chop topped with a Mango chutney.",
                            Image = "lamb-chop.jpg",
                            Name = "Lamb Chop",
                            Price = 19.99m,
                            Tags = "[\"Dinner\"]"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Creamy Mango-flavored delight, served ice cold.",
                            Image = "mango-lassi.jpg",
                            Name = "Mango Lassi",
                            Price = 4.99m,
                            Tags = "[\"Drink\"]"
                        },
                        new
                        {
                            Id = 12,
                            Description = "A refreshing minty cocktail.",
                            Image = "mojito.jpg",
                            Name = "Mojito",
                            Price = 6.99m,
                            Tags = "[\"Drink\",\"Alcoholic\"]"
                        },
                        new
                        {
                            Id = 13,
                            Description = "A classic cocktail with a twist.",
                            Image = "old-fashioned.jpg",
                            Name = "Old Fashioned",
                            Price = 7.99m,
                            Tags = "[\"Drink\",\"Alcoholic\"]"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Delicious whole wheat pasta topped with our zesty pesto sauce.",
                            Image = "pesto-bowtie-pasta.jpg",
                            Name = "Pesto Bowtie Pasta",
                            Price = 12.99m,
                            Tags = "[\"Lunch\",\"Dinner\"]"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Our homemade thin-crust pizza topped with BBQ chicken and our house cheese blend.",
                            Image = "pizza.jpg",
                            Name = "BBQ Chicken Pizza",
                            Price = 14.99m,
                            Tags = "[\"Lunch\",\"Dinner\"]"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Thick-cut Pork Chop with a sweet apple glaze.",
                            Image = "pork-chop.jpg",
                            Name = "Pork Chop",
                            Price = 16.99m,
                            Tags = "[\"Dinner\"]"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Delicious bowl of ramen with pork and vegetables.",
                            Image = "ramen.jpg",
                            Name = "Pork Ramen",
                            Price = 11.99m,
                            Tags = "[\"Lunch\",\"Dinner\"]"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Fresh salad topped with grilled salmon, mixed vegetables, and our house vinaigrette.",
                            Image = "salmon-salad.jpg",
                            Name = "Salmon Salad",
                            Price = 14.99m,
                            Tags = "[\"Lunch\",\"Dinner\",\"Vegetarian\"]"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Seared salmon steak topped with a sweet mango glaze.",
                            Image = "salmon.jpg",
                            Name = "Salmon Steak",
                            Price = 18.99m,
                            Tags = "[\"Dinner\"]"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Delicious chicken tacos with a spicy mango salsa.",
                            Image = "street-tacos.jpg",
                            Name = "Chicken Street Tacos",
                            Price = 9.99m,
                            Tags = "[\"Lunch\",\"Dinner\",\"Spicy\"]"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Fresh grilled veggies on our homemade toasted sourdough.",
                            Image = "veggie-sammy.jpg",
                            Name = "Veggie Sammy",
                            Price = 8.99m,
                            Tags = "[\"Lunch\",\"Dinner\",\"Vegetarian\"]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
