/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoodFoodIdRouteImport } from './routes/food.$foodId'
import { Route as AdminChar123FoodIdChar125RouteImport } from './routes/admin.{-$foodId}'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodFoodIdRoute = FoodFoodIdRouteImport.update({
  id: '/food/$foodId',
  path: '/food/$foodId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChar123FoodIdChar125Route =
  AdminChar123FoodIdChar125RouteImport.update({
    id: '/admin/{-$foodId}',
    path: '/admin/{-$foodId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/{-$foodId}': typeof AdminChar123FoodIdChar125Route
  '/food/$foodId': typeof FoodFoodIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/{-$foodId}': typeof AdminChar123FoodIdChar125Route
  '/food/$foodId': typeof FoodFoodIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/{-$foodId}': typeof AdminChar123FoodIdChar125Route
  '/food/$foodId': typeof FoodFoodIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/admin/{-$foodId}' | '/food/$foodId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/admin/{-$foodId}' | '/food/$foodId'
  id: '__root__' | '/' | '/about' | '/admin/{-$foodId}' | '/food/$foodId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminChar123FoodIdChar125Route: typeof AdminChar123FoodIdChar125Route
  FoodFoodIdRoute: typeof FoodFoodIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/$foodId': {
      id: '/food/$foodId'
      path: '/food/$foodId'
      fullPath: '/food/$foodId'
      preLoaderRoute: typeof FoodFoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/{-$foodId}': {
      id: '/admin/{-$foodId}'
      path: '/admin/{-$foodId}'
      fullPath: '/admin/{-$foodId}'
      preLoaderRoute: typeof AdminChar123FoodIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminChar123FoodIdChar125Route: AdminChar123FoodIdChar125Route,
  FoodFoodIdRoute: FoodFoodIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
