/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignProposalsNoPluginRouteImport } from './routes/design-proposals-no-plugin'
import { Route as DesignProposalsFrontendPluginRouteImport } from './routes/design-proposals-frontend-plugin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoodFoodIdRouteImport } from './routes/food.$foodId'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as AdminChar123FoodIdChar125RouteImport } from './routes/admin.{-$foodId}'

const DesignProposalsNoPluginRoute = DesignProposalsNoPluginRouteImport.update({
  id: '/design-proposals-no-plugin',
  path: '/design-proposals-no-plugin',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignProposalsFrontendPluginRoute =
  DesignProposalsFrontendPluginRouteImport.update({
    id: '/design-proposals-frontend-plugin',
    path: '/design-proposals-frontend-plugin',
    getParentRoute: () => rootRouteImport,
  } as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodFoodIdRoute = FoodFoodIdRouteImport.update({
  id: '/food/$foodId',
  path: '/food/$foodId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => CheckoutRoute,
} as any)
const AdminChar123FoodIdChar125Route =
  AdminChar123FoodIdChar125RouteImport.update({
    id: '/admin/{-$foodId}',
    path: '/admin/{-$foodId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/design-proposals-frontend-plugin': typeof DesignProposalsFrontendPluginRoute
  '/design-proposals-no-plugin': typeof DesignProposalsNoPluginRoute
  '/admin/{-$foodId}': typeof AdminChar123FoodIdChar125Route
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/food/$foodId': typeof FoodFoodIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/design-proposals-frontend-plugin': typeof DesignProposalsFrontendPluginRoute
  '/design-proposals-no-plugin': typeof DesignProposalsNoPluginRoute
  '/admin/{-$foodId}': typeof AdminChar123FoodIdChar125Route
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/food/$foodId': typeof FoodFoodIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/design-proposals-frontend-plugin': typeof DesignProposalsFrontendPluginRoute
  '/design-proposals-no-plugin': typeof DesignProposalsNoPluginRoute
  '/admin/{-$foodId}': typeof AdminChar123FoodIdChar125Route
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/food/$foodId': typeof FoodFoodIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/design-proposals-frontend-plugin'
    | '/design-proposals-no-plugin'
    | '/admin/{-$foodId}'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/food/$foodId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/design-proposals-frontend-plugin'
    | '/design-proposals-no-plugin'
    | '/admin/{-$foodId}'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/food/$foodId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/design-proposals-frontend-plugin'
    | '/design-proposals-no-plugin'
    | '/admin/{-$foodId}'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/food/$foodId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  DesignProposalsFrontendPluginRoute: typeof DesignProposalsFrontendPluginRoute
  DesignProposalsNoPluginRoute: typeof DesignProposalsNoPluginRoute
  AdminChar123FoodIdChar125Route: typeof AdminChar123FoodIdChar125Route
  FoodFoodIdRoute: typeof FoodFoodIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design-proposals-no-plugin': {
      id: '/design-proposals-no-plugin'
      path: '/design-proposals-no-plugin'
      fullPath: '/design-proposals-no-plugin'
      preLoaderRoute: typeof DesignProposalsNoPluginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-proposals-frontend-plugin': {
      id: '/design-proposals-frontend-plugin'
      path: '/design-proposals-frontend-plugin'
      fullPath: '/design-proposals-frontend-plugin'
      preLoaderRoute: typeof DesignProposalsFrontendPluginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/$foodId': {
      id: '/food/$foodId'
      path: '/food/$foodId'
      fullPath: '/food/$foodId'
      preLoaderRoute: typeof FoodFoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/admin/{-$foodId}': {
      id: '/admin/{-$foodId}'
      path: '/admin/{-$foodId}'
      fullPath: '/admin/{-$foodId}'
      preLoaderRoute: typeof AdminChar123FoodIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  DesignProposalsFrontendPluginRoute: DesignProposalsFrontendPluginRoute,
  DesignProposalsNoPluginRoute: DesignProposalsNoPluginRoute,
  AdminChar123FoodIdChar125Route: AdminChar123FoodIdChar125Route,
  FoodFoodIdRoute: FoodFoodIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
